#!/bin/bash
set -euo pipefail

CHEZMOI_CONFIG="${HOME}/.config/chezmoi/chezmoi.toml"
CHEZMOI_SOURCE="/usr/share/chezmoi-source"

mkdir -p "$(dirname "${CHEZMOI_CONFIG}")"

cat > "${CHEZMOI_CONFIG}" << EOF
[chezmoi]
  sourceDir = "${CHEZMOI_SOURCE}"
EOF

exec /usr/bin/chezmoi apply --no-tty --source "${CHEZMOI_SOURCE}"
